// default package
package com.project.bidonline.entity;
// Generated Oct 31, 2016 2:47:09 AM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bid generated by hbm2java
 */
@Entity
@Table(name = "Bid", catalog = "auction")
public class Bid implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2139454821197708991L;
	private Integer id;
	private User user;
	private String itemName;
	private String itemDescription;
	private byte[] itemImage;
	private Integer itemQuantity;
	private Date bidStartDate;
	private Date bidEndDate;
	private Float bidStartPrice;
	private float bidIncrement;
	private Float bidCurrentPrice;
	private String winning;

	public Bid() {
	}

	public Bid(String itemName, Date bidStartDate, Date bidEndDate, float bidIncrement) {
		this.itemName = itemName;
		this.bidStartDate = bidStartDate;
		this.bidEndDate = bidEndDate;
		this.bidIncrement = bidIncrement;
	}

	public Bid(User user, String itemName, String itemDescription, byte[] itemImage, Integer itemQuantity,
			Date bidStartDate, Date bidEndDate, Float bidStartPrice, float bidIncrement, Float bidCurrentPrice,
			String winning) {
		this.user = user;
		this.itemName = itemName;
		this.itemDescription = itemDescription;
		this.itemImage = itemImage;
		this.itemQuantity = itemQuantity;
		this.bidStartDate = bidStartDate;
		this.bidEndDate = bidEndDate;
		this.bidStartPrice = bidStartPrice;
		this.bidIncrement = bidIncrement;
		this.bidCurrentPrice = bidCurrentPrice;
		this.winning = winning;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_seller")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "item_name", nullable = false, length = 65535)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "item_description", length = 65535)
	public String getItemDescription() {
		return this.itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	@Column(name = "item_image")
	public byte[] getItemImage() {
		return this.itemImage;
	}

	public void setItemImage(byte[] itemImage) {
		this.itemImage = itemImage;
	}

	@Column(name = "item_quantity")
	public Integer getItemQuantity() {
		return this.itemQuantity;
	}

	public void setItemQuantity(Integer itemQuantity) {
		this.itemQuantity = itemQuantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bid_start_date", nullable = false, length = 19)
	public Date getBidStartDate() {
		return this.bidStartDate;
	}

	public void setBidStartDate(Date bidStartDate) {
		this.bidStartDate = bidStartDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bid_end_date", nullable = false, length = 19)
	public Date getBidEndDate() {
		return this.bidEndDate;
	}

	public void setBidEndDate(Date bidEndDate) {
		this.bidEndDate = bidEndDate;
	}

	@Column(name = "bid_start_price", precision = 12, scale = 0)
	public Float getBidStartPrice() {
		return this.bidStartPrice;
	}

	public void setBidStartPrice(Float bidStartPrice) {
		this.bidStartPrice = bidStartPrice;
	}

	@Column(name = "bid_increment", nullable = false, precision = 12, scale = 0)
	public float getBidIncrement() {
		return this.bidIncrement;
	}

	public void setBidIncrement(float bidIncrement) {
		this.bidIncrement = bidIncrement;
	}

	@Column(name = "bid_current_price", precision = 12, scale = 0)
	public Float getBidCurrentPrice() {
		return this.bidCurrentPrice;
	}

	public void setBidCurrentPrice(Float bidCurrentPrice) {
		this.bidCurrentPrice = bidCurrentPrice;
	}

	@Column(name = "winning", length = 20)
	public String getWinning() {
		return this.winning;
	}

	public void setWinning(String winning) {
		this.winning = winning;
	}

}
